// GENERATED by tool/gen_data.mjs — do not edit.
class Country {
  const Country(this.code, this.name, this.dialCode);
  final String code;
  final String name;
  final String dialCode;

  String get plusDial => '+$dialCode';

  bool matches(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return true;
    final digits = q.replaceAll(RegExp(r'[^0-9]'), '');
    return name.toLowerCase().contains(q) ||
        code.toLowerCase().contains(q) ||
        dialCode.contains(digits.isEmpty ? q : digits) ||
        plusDial.contains(q);
  }
}

Country? countryByCode(String? code) {
  if (code == null || code.isEmpty) return null;
  for (final x in countries) {
    if (x.code == code) return x;
  }
  return null;
}

const countries = <Country>[
  Country('IQ', 'العراق', '964'),
  Country('SA', 'السعودية', '966'),
  Country('EG', 'مصر', '20'),
  Country('AE', 'الإمارات', '971'),
  Country('JO', 'الأردن', '962'),
  Country('KW', 'الكويت', '965'),
  Country('QA', 'قطر', '974'),
  Country('BH', 'البحرين', '973'),
  Country('OM', 'عُمان', '968'),
  Country('YE', 'اليمن', '967'),
  Country('SY', 'سوريا', '963'),
  Country('LB', 'لبنان', '961'),
  Country('PS', 'فلسطين', '970'),
  Country('LY', 'ليبيا', '218'),
  Country('TN', 'تونس', '216'),
  Country('DZ', 'الجزائر', '213'),
  Country('MA', 'المغرب', '212'),
  Country('SD', 'السودان', '249'),
  Country('MR', 'موريتانيا', '222'),
  Country('AF', 'أفغانستان', '93'),
  Country('AL', 'ألبانيا', '355'),
  Country('AR', 'الأرجنتين', '54'),
  Country('AU', 'أستراليا', '61'),
  Country('AT', 'النمسا', '43'),
  Country('AZ', 'أذربيجان', '994'),
  Country('BD', 'بنغلاديش', '880'),
  Country('BE', 'بلجيكا', '32'),
  Country('BR', 'البرازيل', '55'),
  Country('CA', 'كندا', '1'),
  Country('CN', 'الصين', '86'),
  Country('CO', 'كولومبيا', '57'),
  Country('CZ', 'التشيك', '420'),
  Country('DK', 'الدنمارك', '45'),
  Country('ET', 'إثيوبيا', '251'),
  Country('FI', 'فنلندا', '358'),
  Country('FR', 'فرنسا', '33'),
  Country('DE', 'ألمانيا', '49'),
  Country('GH', 'غانا', '233'),
  Country('GR', 'اليونان', '30'),
  Country('HK', 'هونغ كونغ', '852'),
  Country('IN', 'الهند', '91'),
  Country('ID', 'إندونيسيا', '62'),
  Country('IR', 'إيران', '98'),
  Country('IE', 'أيرلندا', '353'),
  Country('IL', 'إسرائيل', '972'),
  Country('IT', 'إيطاليا', '39'),
  Country('JP', 'اليابان', '81'),
  Country('KZ', 'كازاخستان', '7'),
  Country('KE', 'كينيا', '254'),
  Country('KR', 'كوريا الجنوبية', '82'),
  Country('MY', 'ماليزيا', '60'),
  Country('MX', 'المكسيك', '52'),
  Country('NL', 'هولندا', '31'),
  Country('NG', 'نيجيريا', '234'),
  Country('NO', 'النرويج', '47'),
  Country('PK', 'باكستان', '92'),
  Country('PH', 'الفلبين', '63'),
  Country('PL', 'بولندا', '48'),
  Country('PT', 'البرتغال', '351'),
  Country('RU', 'روسيا', '7'),
  Country('SG', 'سنغافورة', '65'),
  Country('ZA', 'جنوب أفريقيا', '27'),
  Country('ES', 'إسبانيا', '34'),
  Country('SE', 'السويد', '46'),
  Country('CH', 'سويسرا', '41'),
  Country('TH', 'تايلاند', '66'),
  Country('TR', 'تركيا', '90'),
  Country('UA', 'أوكرانيا', '380'),
  Country('GB', 'بريطانيا', '44'),
  Country('US', 'أمريكا', '1'),
  Country('UZ', 'أوزبكستان', '998'),
  Country('VN', 'فيتنام', '84'),
];
