// Generates lib/data/countries.dart from the Vue app's data/countries.js.
// Run from flutter-app/: node tool/gen_data.mjs
import { writeFileSync, mkdirSync } from 'node:fs'
import { countries } from '../../mobile-app/src/data/countries.js'

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
const rows = countries.map((c) => `  Country('${esc(c.code)}', '${esc(c.name)}', '${esc(c.dialCode)}'),`).join('\n')

mkdirSync('lib/data', { recursive: true })
writeFileSync(
  'lib/data/countries.dart',
  `// GENERATED by tool/gen_data.mjs — do not edit.\n` +
    `class Country {\n  const Country(this.code, this.name, this.dialCode);\n  final String code;\n  final String name;\n  final String dialCode;\n}\n\n` +
    `const countries = <Country>[\n${rows}\n];\n`
)
console.log(`wrote ${countries.length} countries`)
